// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function triangular(n) {
  if (n <= 0) {
    return 0;
  } else {
    return n + triangular(n - 1 | 0) | 0;
  }
}

exports.triangular = triangular;
/* No side effect */
